name: Troll
version: 1.0
main: de.eintosti.troll.Troll
description: Time to have a blast
author: einTosti

commands:
    Troll:
       description: Time to have a blast
       usage: /<command>

permissions:
    troll.use:
        description: Not everybody can have all of the fun...
        default: OP
