name: Troll
version: 1.1
main: de.eintosti.troll.Troll
description: Heute ist Trolling angesagt!
author: einTosti

commands:
    Troll:
       description: Heute ist Trolling angesagt!
       usage: /<command>

permissions:
    troll.use:
        description: Nicht jeder darf abgehoben sein...
        default: OP
