name: Troll
version: 1.1
main: de.eintosti.troll.Troll
description: Time to have a blast
author: einTosti
api-version: 1.13

commands:
    Troll:
       description: Time to have a blast
       usage: /<command>

permissions:
    troll.use:
        description: Not everybody can have all of the fun...
        default: OP
